//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDating.Components {
    
    public partial class DatePicker {
        protected System.Web.UI.HtmlControls.HtmlGenericControl divDatePicker;
        protected System.Web.UI.WebControls.DropDownList dropDay;
        protected System.Web.UI.WebControls.DropDownList dropMonth;
        protected System.Web.UI.WebControls.DropDownList dropYear;
    }
}
